Restruct
piybeep/piybeep-c-v2 pull request #96
Opened 2023-12-26 18:14 UTC by Wycctrujjla109121

2024-01-17 20:51 UTC, danyatochkaru requested changes

2024-01-17 20:51 UTC, danyatochkaru commented on src/styles/globals.scss
> +            /* $main-color */
кажется, тут что то не так. нужно сверить с дизайном

2024-01-17 20:51 UTC, danyatochkaru commented on src/modules/pages/studio/Spa/Spa.tsx
> +					text="SPA - single page applications (одностраничные приложения) - это
лучше вынести в константы, иначе потом при правках далеко лезть придётся

2024-01-17 20:51 UTC, danyatochkaru commented on src/modules/pages/studio/Steps/Steps.module.scss
> +    //max-width: 1360px;
почистить

2024-01-17 20:51 UTC, danyatochkaru commented on src/modules/pages/studio/Team/components/Person/Person.module.scss
> +    //cursor: pointer;
почистить

2024-01-19 10:14 UTC, Wycctrujjla109121 commented on src/styles/globals.scss
> +            /* $main-color */
Не смог понять что это на странице

2024-01-19 10:54 UTC, Wycctrujjla109121 commented on src/modules/OurProjects/OurProjects.tsx
> +		setGroupCount(() => (width >= 1024 ? 3 : width >= 768 ? 2 : width >= 360 ? 2 : 1));
Нет не является, проверь получше при обновлении страницы это срабатывает

2024-01-22 23:49 UTC, danyatochkaru approved these changes

2024-01-23 17:12 UTC, merged